=== CMDigital/cmdigital.github.com/data/data.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:complexType name="projectItem">
    <xs:attribute name="id"   type="xs:ID" use="required"/>
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="srcURL" type="xs:anyURI"/>
    <xs:attribute name="url" type="xs:anyURI"/>
  </xs:complexType>

  <xs:complexType name="projects">
    <xs:sequence>
      <xs:element name="project" type="projectItem"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="user">
    <xs:attribute name="id" type="xs:ID"/>
    <xs:attribute name="name" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="users">
    <xs:sequence>
      <xs:element name="user" type="user" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="scheduleItem">
    <xs:attribute name="project"/>
    <xs:attribute name="user"/>
    <xs:attribute name="time"/>
  </xs:complexType>

  <xs:complexType name="schedule">
    <xs:sequence>
      <xs:element name="item" type="scheduleItem" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="date"/>
  </xs:complexType>

  <xs:complexType name="timetables">
    <xs:sequence>
      <xs:element name="schedule" type="schedule"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="common">
    <xs:sequence>
      <xs:element name="projects" type="projects"/>
      <xs:element name="users" type="users"/>
      <xs:element name="timetables" type="timetables"/>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="labs" type="common"/>
</xs:schema>

=== CMDigital/cmdigital.github.com/data/data.xml
<!--<labs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"-->
      <!--xsi:noNamespaceSchemaLocation="data.xsd">-->
<!DOCTYPE source [

<!ELEMENT project ANY>
<!ATTLIST project id ID #REQUIRED>

<!ELEMENT user ANY>
<!ATTLIST user id ID #REQUIRED>
]>
<labs>
  <projects>
    <project id="p1"   name="pubMap"                       srcURL ="https://github.com/toastman/pubMap" url=""/>
    <project id="p2"   name="mindMap"                      srcURL ="https://github.com/CMDigital/mindMap" url=""/>
    <project id="p3"   name="Нічого не робити і бути злим" srcURL ="" url=""/>
    <project id="p4"   name="Математичний гурток"          srcURL ="" url=""/>
    <project id="p5"   name="П'ятнадцятка"                 srcURL ="https://github.com/CMDigital/Game-of-15" url=""/>
    <project id="p6"   name="Upload addon"                 srcURL ="" url=""/>
    <project id="p7"   name="Печенюшки"                    srcURL ="" url=""/>
    <project id="p8"   name="Системи віртуалізації"        srcURL ="" url=""/>
    <project id="p9"   name="Animation framework"          srcURL ="" url=""/>
    <project id="p10"  name="Inventory"                    srcURL ="http://hg.citymedia.no/ruby/cminventory/" url="http://inventory.citymedia.no/"/>
    <project id="p11"  name="RealGo"                       srcURL ="" url=""/>
    <project id="p12"  name="Туалетне радіо"               srcURL ="" url=""/>
    <project id="p13"  name="Компілятори, курс лекцій"     srcURL ="" url=""/>
    <project id="p14"  name="Автоматичне тестування"       srcURL ="" url=""/>
    <project id="p15"  name="Системи БД"                   srcURL ="" url=""/>
    <project id="p16"  name="Close the door"               srcURL ="" url=""/>
    <project id="p17"  name="Klyaksa"                      srcURL ="https://github.com/CMDigital/Klyaksa" url=""/>
  </projects>

  <users>
    <user id="u1"  name="Андрій   "/>
    <user id="u2"  name="Сашко    "/>
    <user id="u3"  name="Михайло  "/>
    <user id="u4"  name="Валерійко"/>
    <user id="u5"  name="Павло    "/>
    <user id="u6"  name="Paul     "/>
    <user id="u7"  name="Олексій  "/>
    <user id="u8"  name="Жанна    "/>
    <user id="u9"  name="Віталік  "/>
    <user id="u10" name="Юрко     "/>
    <user id="u11" name="Устим    "/>
    <user id="u12" name="Іван     "/>
    <user id="u13" name="Оля      "/>
    <user id="u14" name="Христя   "/>
    <user id="u15" name="Богдан   "/>
    <user id="u16" name="Олег     "/>
    <user id="u17" name="Євген    "/>
    <user id="u18" name="Артем    "/>
    <user id="u19" name="Надя     "/>
    <user id="u20" name="Роксолана"/>
    <user id="u21" name="Юля      "/>
  </users>
 <timetables>
   <schedule date ="Березень 2012 ">
     <item project="p1" user="u1" time="1-3"/>
     <item project="" user="u2" time=""/>
     <item project="" user="u3" time=""/>
     <item project="" user="u4" time=""/>
     <item project="" user="u5" time=""/>
     <item project="" user="u6" time=""/>
     <item project="" user="u7" time=""/>
     <item project="" user="u8" time=""/>
     <item project="" user="u9" time=""/>
     <item project="" user="u10" time=""/>
     <item project="" user="u11" time=""/>
     <item project="p17" user="u12" time="14-16"/>
     <item project="" user="u13" time=""/>
     <item project="" user="u14" time=""/>
     <item project="" user="u15" time=""/>
     <item project="" user="u16" time=""/>
     <item project="" user="u17" time=""/>
     <item project="" user="u18" time=""/>
     <item project="" user="u19" time=""/>
     <item project="" user="u20" time=""/>
     <item project="" user="u21" time=""/>
   </schedule>

   <schedule date ="Лютий 2012 ">
     <item project="p1" user="u1" time="1-3"/>
     <item project="p15" user="u2" time="16, 17, 21"/>
     <item project="" user="u3" time=""/>
     <item project="" user="u4" time=""/>
     <item project="" user="u5" time=""/>
     <item project="" user="u6" time=""/>
     <item project="p11" user="u7" time="14, 28, 29"/>
     <item project="p16" user="u8" time="15-17"/>
     <item project="p2" user="u9" time="20,21,22"/>
     <item project="p8" user="u10" time="20-22"/>
     <item project="p9" user="u11" time="15-17"/>
     <item project="p10" user="u12" time="1-3"/>
     <item project="p11" user="u13" time="13-15"/>
     <item project="p10" user="u14" time="1-3"/>
     <item project="p3" user="u15" time="∞"/>
     <item project="p3" user="u16" time="∞"/>
     <item project="p13" user="u17" time="27-29"/>
     <item project="p14" user="u18" time="27-29"/>
     <item project="" user="u19" time=""/>
     <item project="" user="u20" time=""/>
     <item project="" user="u21" time=""/>
   </schedule>

   <schedule date ="Січень 2012">
     <item project="p1" user="u1" time="10-12"/>
     <item project="p1" user="u2" time="18-20"/>
     <item project="p2" user="u3" time="12,13,16"/>
     <item project="p3" user="u4" time="∞"/>
     <item project="p4" user="u5" time="11,18,25"/>
     <item project="p5" user="u6" time="10,11,18"/>
     <item project="p6" user="u7" time="12,13,16"/>
     <item project="p7" user="u8" time="16-18"/>
     <item project="p2" user="u9" time="23-25"/>
     <item project="p8" user="u10" time="16-18"/>
     <item project="p9" user="u11" time="26-28"/>
     <item project="p10" user="u12" time="16-18"/>
     <item project="p11" user="u13" time="27,30,31"/>
     <item project="p5" user="u14" time="16-18"/>
     <item project="p3" user="u15" time="∞"/>
     <item project="p12" user="u16" time="11-13"/>
     <item project="p13" user="u17" time="27,30,31"/>
     <item project="p14" user="u18" time="18-20"/>
     <item project="p14" user="u19" time="18-20"/>
     <item project="" user="u20" time=""/>
     <item project="p3" user="u21" time="∞"/>
    </schedule>

  </timetables>
</labs>
